modLoader="javafml"
loaderVersion="[43,)"
license="The MIT License"

[[mods]]
modId="renderengine"
version="${file.jarVersion}"
displayName="Render Engine"
updateJSONURL=""
displayURL=""
authors="Maydaymemory and Arcomit"
description='''
'''

[[dependencies.renderengine]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.renderengine]]
modId="minecraft"
mandatory=true
versionRange="[1.19.1, 1.19.2)"
ordering="NONE"
side="BOTH"
